### ISSUE TITLE
Piecewise linear growth rate models outputting unrealistically large rates for kg/month

### ISSUE THREAD

**Issue by kirbybartlett** [maricultura/maricultura-app#1]
Growth models and associated species coefficients: 
<img width="900" alt="Screen Shot 2020-01-27 at 9 10 27 PM" src="https://user-images.githubusercontent.com/43867033/73237160-9a938a80-4149-11ea-8c7a-b86dd25c27d6.png">

<img width="588" alt="Screen Shot 2020-01-27 at 9 10 41 PM" src="https://user-images.githubusercontent.com/43867033/73237162-9a938a80-4149-11ea-81f2-325b9b4055dc.png">

**Comment by kirbybartlett** [comment]
https://github.com/maricultura/maricultura-app/blob/0d34c1c435134e4b332435b4724f6da1c95e638f/maricultura-app/app.R#L23-L34

https://github.com/maricultura/maricultura-app/blob/2fdbfc6927b24560c7e81a2d839194fb479a1f57/maricultura-app/app.R#L165-L173

https://github.com/maricultura/maricultura-app/blob/2fdbfc6927b24560c7e81a2d839194fb479a1f57/maricultura-app/app.R#L678-L706

**Comment by jcvdav** [comment]
Closed?
